export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const MANUAL_PURCHASE = 'MANUAL_PURCHASE';
export const AUTO_PURCHASE = 'AUTO_PURCHASE';
export const CREATE_LOTTOS = 'CREATE_LOTTOS';
export const DECIDE_WINNER = 'DECIDE_WINNER';
export const CALCULATE_PROFIT = 'CALCULATE_PROFIT';
export const RESTART = 'RESTART';
