export const LOTTO_SYSTEM = Object.freeze({
  MIN_PURCHASE_PRICE: 1000,
  SIZE: Object.freeze({
    MAX_LOTTO_NUMBER: 45,
    MIN_LOTTO_NUMBER: 1,
    MAX_LENGTH: 6,
  }),
  FIVE_WITH_BONUS_MATCH_IDX: 7,
  SIX_MATCH: 6,
  FIVE_WITH_BONUS_MATCH: 5.5,
  FIVE_MATCH: 5,
  FOUR_MATCH: 4,
  THREE_MATCH: 3,
});

export const PRIZE_OF_MATCH_COUNT = Object.freeze({
  [LOTTO_SYSTEM.SIX_MATCH]: 2000000000,
  [LOTTO_SYSTEM.FIVE_WITH_BONUS_MATCH_IDX]: 30000000,
  [LOTTO_SYSTEM.FIVE_MATCH]: 1500000,
  [LOTTO_SYSTEM.FOUR_MATCH]: 50000,
  [LOTTO_SYSTEM.THREE_MATCH]: 5000,
});
