const NUMBER = Object.freeze({
  LOTTO_PRICE: 1000,
  LOTTO_START_NUMBER: 1,
  LOTTO_END_NUMBER: 45,
  LOTTO_NUMBERS_LENGTH: 6,
  LOTTO_BONUS_LENGTH: 1,
  LOTTO_MAX_COUNT: 1000,
});

export default NUMBER;
