import { VALUES } from '../constants.js';

export const getPriceByRank = (rank = VALUES.RANK.LOSE) => {
  const price = {
    [VALUES.RANK.FIRST]: VALUES.WINNING_PRICE.FIRST,
    [VALUES.RANK.SECOND]: VALUES.WINNING_PRICE.SECOND,
    [VALUES.RANK.THIRD]: VALUES.WINNING_PRICE.THIRD,
    [VALUES.RANK.FOURTH]: VALUES.WINNING_PRICE.FOURTH,
    [VALUES.RANK.FIFTH]: VALUES.WINNING_PRICE.FIFTH,
    [VALUES.RANK.LOSE]: VALUES.WINNING_PRICE.LOSE,
  };

  return price[rank];
};

export const getRankByMatchCount = (matchCount = VALUES.MATCHED_COUNT.ZERO) => {
  const rank = {
    [VALUES.MATCHED_COUNT.SIX]: VALUES.RANK.FIRST,
    [VALUES.MATCHED_COUNT.FIVE]: VALUES.RANK.THIRD,
    [VALUES.MATCHED_COUNT.FOUR]: VALUES.RANK.FOURTH,
    [VALUES.MATCHED_COUNT.THREE]: VALUES.RANK.FIFTH,
    [VALUES.MATCHED_COUNT.TWO]: VALUES.RANK.LOSE,
    [VALUES.MATCHED_COUNT.ONE]: VALUES.RANK.LOSE,
    [VALUES.MATCHED_COUNT.ZERO]: VALUES.RANK.LOSE,
  };

  return rank[matchCount];
};
