export {
  UNIT_AMOUNT,
  MIN_LOTTO_NUMBER,
  MAX_LOTTO_NUMBER,
  LOTTO_NUMBER_COUNT,
  BONUS_NUMBER_COUNT,
  WINNING_NUMBER_COUNT,
  PRIZE_MONEY,
  LOTTO_TYPE_AUTO,
  LOTTO_TYPE_MANUAL,
} from './standard.js';
export {
  MSG_INVALID_PURCHASE_AMOUNT,
  MSG_BLANK_INPUT,
  MSG_OUT_RANGED_LOTTO_NUMBERS,
  MSG_DUPLICATED_LOTTO_NUMBERS,
} from './alertMessage.js';
