export const LOTTO_SETTING = Object.freeze({
  MIN_RANDOM_NUMBER: 1,
  MAX_RANDOM_NUMBER: 45,
  PRICE: 1000,
  LOTTO_NUMBER_LENGTH: 6,
  BONUS_NUMBER_LENGTH: 1,
  RACKING_START_NUMBER: 5,
  WINNING_MIN_MATCH_NUMBER: 3,
});
