const WINNING_NUMBERS_COUNT = 6;

const WINNING_NUMBER_MAX_LENGTH = 2;

const RESULT_EVENT_NAME = 'calculateResult';

const WINNING_INPUTS_FORM_SELECTORS = Object.freeze({
  WINNING_NUMBER_INPUTS: '.number-input.winning',
  BONUS_NUMBER_INPUT: '.number-input.bonus',
  RESULT_BUTTON: '.result-button',
});

export {
  WINNING_NUMBERS_COUNT,
  WINNING_NUMBER_MAX_LENGTH,
  RESULT_EVENT_NAME,
  WINNING_INPUTS_FORM_SELECTORS,
};
