export const LOTTO_DEFINITION = {
  ONE_PRICE: 1000,
  NUMBER_COUNTS: 6,
  MIN_NUMBER: 1,
  MAX_NUMBER: 45,
};

export const LOTTO_PRIZE_DEFINITION = {
  FIRST_PRIZE: 'FIRST_PRIZE',
  SECOND_PRIZE: 'SECOND_PRIZE',
  THIRD_PRIZE: 'THIRD_PRIZE',
  FOURTH_PRIZE: 'FOURTH_PRIZE',
  FIFTH_PRIZE: 'FIFTH_PRIZE',
  NONE: 'NONE',
};
