export const LOTTO_DEFINITION = {
  ONE_PRICE: 1000,
  NUMBER_COUNTS: 6,
  MIN_NUMBER: 1,
  MAX_NUMBER: 45,
};

export const LOTTO_PRIZE_DEFINITION = {
  FIRST_PRIZE: 'FIRST_PRIZE',
  SECOND_PRIZE: 'SECOND_PRIZE',
  THIRD_PRIZE: 'THIRD_PRIZE',
  FOURTH_PRIZE: 'FOURTH_PRIZE',
  FIFTH_PRIZE: 'FIFTH_PRIZE',
  NONE: 'NONE',
};

export const LOTTO_PRIZE_MONEY_DEFINITION = {
  FIRST_PRIZE: 2_000_000_000,
  SECOND_PRIZE: 30_000_000,
  THIRD_PRIZE: 1_500_000,
  FOURTH_PRIZE: 50_000,
  FIFTH_PRIZE: 5_000,
  NONE: 0,
};
