const TICKET_NUMBERS_LENGTH = 6;
const TICKET_PRICE = 1000;
const TICKET_MIN_NUMBER = 1;
const TICKET_MAX_NUMBER = 45;

export {
  TICKET_NUMBERS_LENGTH,
  TICKET_PRICE,
  TICKET_MIN_NUMBER,
  TICKET_MAX_NUMBER,
};
