export const LOTTO_SETTINGS = {
  LOTTO_NUMBER_SIZE: 6,
  BONUS_NUMBER_SIZE: 1,

  MIN_LOTTO_NUMBER: 1,
  MAX_LOTTO_NUMBER: 45,
  LOTTO_PRICE: 1000,
}

export const UI_SETTINGS = {
  DEFAULT_VISIBILITY: false,
}

export const PRIZES = {
  FIRST: 2000000000,
  SECOND: 30000000,
  THIRD: 1500000,
  FOURTH: 50000,
  FIFTH: 5000,
}

export const WIN_COUNTS = {
  WINNING_COUNT_THREE: 3,
  WINNING_COUNT_FOUR: 4,
  WINNING_COUNT_FIVE: 5,
  WINNING_COUNT_SIX: 6,

  BONUS_COUNT_ZERO: 0,
  BONUS_COUNT_ONE: 1,
}

export const RANKS = {
  FIRST: 'first',
  SECOND: 'second',
  THIRD: 'third',
  FOURTH: 'fourth',
  FIFTH: 'fifth',
}
